---
- name: Instalando o Argocd
  hosts: webservers
  become: no

  tasks:
  - name: Criando o Namespace
    command: >
      kubectl create namespace argocd

  - name: Instalando o Argocd
    command: >
      kubectl apply 
      -n argocd 
      -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  
  - name: Espera o Argocd Executar
    command: >
      kubectl wait
      --for=condition=available
      --timeout=180s deployment 
      --all
      -n argocd

  - name: Expondo as portas
    command: >
      kubectl port-forward svc/argocd-server 
      -n argocd 
      --address 0.0.0.0 8080:443