---
- name: Instalar e configurar Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Instalar o Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Garantir que o Nginx esteja rodando
      service:
        name: nginx
        state: started