---
- name: Iniciando o Argocd
  hosts: webservers
  become: yes

  tasks:
  - name: Expondo as portas
    command: >
      kubectl port-forward svc/argocd-server 
      -n argocd 
      --address 0.0.0.0 8080:443